
let prog=getCollection("progressData")[0]||{papers:0,streak:0,target:"",history:[],subjects:{}};
function saveProg(){setCollection("progressData",[prog])}
function renderProgress(){$("paperCount").textContent=prog.papers;$("streak").textContent=prog.streak;$("targetMessage").textContent=prog.target?`Target Grade: ${prog.target}`:"—";$("progressSummary").textContent=Object.keys(prog.subjects).length?`${Object.keys(prog.subjects).length} subjects tracked`:"No subject progress recorded yet.";$("historyList").innerHTML=(prog.history||[]).slice(-8).reverse().map(x=>`<li>✅ ${esc(x)}</li>`).join("")||"<li class='muted'>No completed sessions yet.</li>";$("subjectProgress").innerHTML=Object.entries(prog.subjects).map(([s,v])=>`<div class="card"><div class="actions" style="justify-content:space-between"><strong>${esc(s)}</strong><span>${v}%</span></div><div class="progressbar"><span style="width:${v}%"></span></div><div class="actions" style="margin-top:10px"><button class="btn small secondary" onclick="changeProgress('${esc(s)}',-10)">−10</button><button class="btn small" onclick="changeProgress('${esc(s)}',10)">+10</button></div></div>`).join("")||'<div class="empty">Add a subject to start tracking.</div>'}
function addSubject(){const s=$("progressSubject").value.trim();if(!s)return;if(!(s in prog.subjects))prog.subjects[s]=0;saveProg();$("progressSubject").value="";renderProgress()}
function changeProgress(s,n){prog.subjects[s]=Math.max(0,Math.min(100,(prog.subjects[s]||0)+n));saveProg();renderProgress()}
function addPaper(){prog.papers++;saveProg();renderProgress()}
function completeGoal(){const today=new Date().toLocaleDateString("en-GB");if(prog.history.at(-1)!==today){prog.streak++;prog.history.push(today);saveProg();renderProgress()}}
function saveTargetGrade(){prog.target=$("targetGrade").value;saveProg();renderProgress()}
let seconds=1500,timer=null;function timerRender(){const m=Math.floor(seconds/60),s=seconds%60;$("timer").textContent=`${m}:${String(s).padStart(2,"0")}`}function startTimer(){if(timer)return;timer=setInterval(()=>{if(seconds<=0){clearInterval(timer);timer=null;alert("Revision session complete!");return}seconds--;timerRender()},1000)}function resetTimer(){clearInterval(timer);timer=null;seconds=1500;timerRender()}
document.addEventListener("DOMContentLoaded",()=>{if(!$("progressPage"))return;$("addSubject").onclick=addSubject;$("addPaper").onclick=addPaper;$("completeGoal").onclick=completeGoal;$("saveTarget").onclick=saveTargetGrade;$("startTimer").onclick=startTimer;$("resetTimer").onclick=resetTimer;renderProgress();timerRender()});
