/* GCSE OnTrack — Progress + Custom Timer */
let progressData=getCollection("progressData")[0]||{papers:0,streak:0,target:"",history:[],subjects:{},timerMinutes:25,timerSeconds:0};
function saveProgress(){setCollection("progressData",[progressData])}
let timerInterval=null;
let remainingSeconds=(Number(progressData.timerMinutes)||25)*60+(Number(progressData.timerSeconds)||0);
const $=id=>document.getElementById(id);
function renderProgress(){if(!$("progressPage"))return;$("paperCount").textContent=progressData.papers;$("streak").textContent=progressData.streak;$("targetMessage").textContent=progressData.target?`Target Grade: ${progressData.target}`:"—";$("progressSummary").textContent=Object.keys(progressData.subjects).length?`${Object.keys(progressData.subjects).length} subjects tracked`:"No subject progress recorded yet.";$("historyList").innerHTML=(progressData.history||[]).slice(-8).reverse().map(x=>`<li>✅ ${esc(x)}</li>`).join("")||"<li class='muted'>No completed sessions yet.</li>";$("subjectProgress").innerHTML=Object.entries(progressData.subjects).map(([s,v])=>`<div class="card"><div class="actions" style="justify-content:space-between"><strong>${esc(s)}</strong><span>${v}%</span></div><div class="progressbar"><span style="width:${v}%"></span></div><div class="actions" style="margin-top:10px"><button class="btn small secondary" data-progress="minus" data-subject="${encodeURIComponent(s)}">−10</button><button class="btn small" data-progress="plus" data-subject="${encodeURIComponent(s)}">+10</button></div></div>`).join("")||'<div class="empty">Add a subject to start tracking.</div>';renderTimer()}
function addSubject(){const s=$("progressSubject").value.trim();if(!s)return alert("Enter a subject.");if(!(s in progressData.subjects))progressData.subjects[s]=0;saveProgress();$("progressSubject").value="";renderProgress()}
function changeProgress(s,n){if(!(s in progressData.subjects))return;progressData.subjects[s]=Math.max(0,Math.min(100,progressData.subjects[s]+n));saveProgress();renderProgress()}
function addPaper(){progressData.papers++;saveProgress();renderProgress()}
function completeGoal(){const today=new Date().toLocaleDateString("en-GB");if(progressData.history.at(-1)!==today){progressData.streak++;progressData.history.push(today);saveProgress();renderProgress()}}
function saveTargetGrade(){progressData.target=$("targetGrade").value;saveProgress();renderProgress()}
function renderTimer(){const safe=Math.max(0,remainingSeconds),m=Math.floor(safe/60),s=safe%60;if($("timer"))$("timer").textContent=`${String(m).padStart(2,"0")}:${String(s).padStart(2,"0")}`;if($("timerMinutes")&&timerInterval===null)$("timerMinutes").value=m;if($("timerSeconds")&&timerInterval===null)$("timerSeconds").value=s}
function syncTimerInputs(){pauseTimer();const m=Math.max(0,Number($("timerMinutes")?.value)||0),s=Math.max(0,Math.min(59,Number($("timerSeconds")?.value)||0));progressData.timerMinutes=m;progressData.timerSeconds=s;remainingSeconds=m*60+s;saveProgress();renderTimer()}
function startTimer(){if(timerInterval!==null)return;if(remainingSeconds<=0){syncTimerInputs();if(remainingSeconds<=0)return alert("Set a timer duration first.")}timerInterval=setInterval(()=>{if(remainingSeconds<=0){pauseTimer();alert("Revision session complete!");return}remainingSeconds--;renderTimer()},1000)}
function pauseTimer(){if(timerInterval!==null){clearInterval(timerInterval);timerInterval=null}}
function resetTimer(){pauseTimer();remainingSeconds=(Number(progressData.timerMinutes)||25)*60+(Number(progressData.timerSeconds)||0);renderTimer()}
function applyTimerPreset(minutes){pauseTimer();progressData.timerMinutes=minutes;progressData.timerSeconds=0;remainingSeconds=minutes*60;saveProgress();renderTimer()}
document.addEventListener("DOMContentLoaded",()=>{if(!$("progressPage"))return;$("addSubject")?.addEventListener("click",addSubject);$("addPaper")?.addEventListener("click",addPaper);$("completeGoal")?.addEventListener("click",completeGoal);$("saveTarget")?.addEventListener("click",saveTargetGrade);$("setTimer")?.addEventListener("click",syncTimerInputs);$("startTimer")?.addEventListener("click",startTimer);$("pauseTimer")?.addEventListener("click",pauseTimer);$("resetTimer")?.addEventListener("click",resetTimer);document.querySelectorAll("[data-timer-preset]").forEach(b=>b.addEventListener("click",()=>applyTimerPreset(Number(b.dataset.timerPreset))));$("subjectProgress")?.addEventListener("click",e=>{const b=e.target.closest("[data-progress]");if(!b)return;changeProgress(decodeURIComponent(b.dataset.subject),b.dataset.progress==="plus"?10:-10)});if($("targetGrade"))$("targetGrade").value=progressData.target||"";if($("timerMinutes"))$("timerMinutes").value=progressData.timerMinutes||25;if($("timerSeconds"))$("timerSeconds").value=progressData.timerSeconds||0;renderProgress()});
window.addEventListener("beforeunload",pauseTimer);
