/* GCSE OnTrack — Resources engine */
const RESOURCE_KEY="resources";
let resources=getCollection(RESOURCE_KEY), currentSearch="", currentSubject="All Subjects", currentSort="newest", openNewTab=true, showArchived=false, showDeleted=false;
const $=id=>document.getElementById(id);
const COLOURS={"Maths":"#2563eb","English":"#7c3aed","Biology":"#16a34a","Chemistry":"#06b6d4","Physics":"#f59e0b","History":"#dc2626","Geography":"#059669","Business":"#9333ea","Computer Science":"#0ea5e9"};
function normalise(r){return {id:r.id||uid("res"),shortId:r.shortId||Math.random().toString(36).slice(2,8).toUpperCase(),title:String(r.title||"Untitled"),url:String(r.url||""),subject:r.subject||"General",tag:String(r.tag||""),note:String(r.note||""),priority:/^(High|Medium|Low)$/.test(r.priority)?r.priority:"Medium",rating:Math.max(1,Math.min(5,Number(r.rating)||3)),favourite:!!r.favourite,pinned:!!r.pinned,archived:!!r.archived,deleted:!!r.deleted,deletedDate:r.deletedDate||null,clicks:Number(r.clicks)||0,created:r.created||Date.now(),lastEdited:r.lastEdited||null,lastOpened:r.lastOpened||null}}
resources=resources.map(normalise);setCollection(RESOURCE_KEY,resources);
function saveResources(){setCollection(RESOURCE_KEY,resources)}
function addResource(){const subject=$("subjectInput")?.value,title=$("titleInput")?.value.trim(),raw=$("urlInput")?.value.trim();if(!subject)return alert("Choose a subject.");if(!title)return alert("Enter a resource title.");if(!raw)return alert("Enter a resource link.");const url=/^https?:\/\//i.test(raw)?raw:"https://"+raw;try{new URL(url)}catch{return alert("Enter a valid URL.")}if(resources.some(r=>!r.deleted&&r.url===url))return alert("That resource is already in your library.");resources.unshift({id:uid("res"),shortId:Math.random().toString(36).slice(2,8).toUpperCase(),title,url,subject,tag:$("tagInput").value.trim(),note:$("noteInput").value.trim(),priority:$("priorityInput").value,rating:Number($("ratingInput").value),favourite:false,pinned:false,archived:false,deleted:false,deletedDate:null,clicks:0,created:Date.now(),lastEdited:null,lastOpened:null});saveResources();clearForm();showArchived=false;showDeleted=false;renderResources()}
function clearForm(){["titleInput","urlInput","tagInput","noteInput"].forEach(id=>{if($(id))$(id).value=""});if($("subjectInput"))$("subjectInput").value="";if($("priorityInput"))$("priorityInput").value="Medium";if($("ratingInput"))$("ratingInput").value="3"}
function getFilteredResources(){let list=resources.filter(r=>showDeleted?r.deleted:showArchived?r.archived&&!r.deleted:!r.archived&&!r.deleted);if(currentSearch){const q=currentSearch.toLowerCase();list=list.filter(r=>[r.title,r.subject,r.tag,r.note,r.url,r.priority].join(" ").toLowerCase().includes(q))}if(currentSubject!=="All Subjects")list=list.filter(r=>r.subject===currentSubject);const p={High:3,Medium:2,Low:1},sorters={newest:(a,b)=>b.created-a.created,oldest:(a,b)=>a.created-b.created,alphabetical:(a,b)=>a.title.localeCompare(b.title),mostOpened:(a,b)=>b.clicks-a.clicks,recentlyEdited:(a,b)=>(b.lastEdited||0)-(a.lastEdited||0),favourites:(a,b)=>Number(b.favourite)-Number(a.favourite),rating:(a,b)=>b.rating-a.rating,priority:(a,b)=>p[b.priority]-p[a.priority]};const sorter=sorters[currentSort]||sorters.newest;return list.sort((a,b)=>Number(b.pinned)-Number(a.pinned)||sorter(a,b))}
function renderResources(){const list=getFilteredResources(),grid=$("resourceGrid");if(!grid)return;$("resultsText").textContent=`${list.length} shown • ${resources.length} total • ${resources.filter(r=>r.archived&&!r.deleted).length} archived • ${resources.filter(r=>r.deleted).length} deleted`;grid.innerHTML="";if(!list.length){grid.innerHTML=`<div class="empty"><h2>${showDeleted?"Recycle Bin is empty":showArchived?"Archive is empty":"No resources found"}</h2><p>Try another filter or add a resource.</p></div>`;updateResourceStats();return}list.forEach(r=>{const card=document.createElement("article");card.className="card";card.style.borderLeft=`7px solid ${COLOURS[r.subject]||"var(--primary)"}`;let host="";try{host=new URL(r.url).hostname.replace(/^www\./,"")}catch{}const age=Math.floor((Date.now()-r.created)/86400000);card.innerHTML=`<div class="actions">${r.pinned?'<span class="badge" style="background:#f59e0b">📌 PINNED</span>':""}${age<7&&!r.deleted?'<span class="badge" style="background:#16a34a">🆕 NEW</span>':""}<span class="badge">${esc(r.subject)}</span><span class="badge">${esc(r.priority)} Priority</span><span class="badge">⭐ ${r.rating}/5</span></div><h2>${esc(r.title)}</h2><div class="muted">${esc(r.shortId)} ${r.tag?`• ${esc(r.tag)}`:""}</div><p>${esc(r.note)||'<span class="muted">No notes.</span>'}</p><a href="${esc(r.url)}" target="${openNewTab?"_blank":"_self"}" rel="noopener" onclick="trackResourceOpen('${r.id}')">${esc(r.url)}</a><div class="muted" style="margin-top:7px">🌐 ${esc(host)}</div><div class="actions" style="margin-top:16px">${r.deleted?`<button class="btn success small" onclick="restoreDeletedResource('${r.id}')">♻ Restore</button><button class="btn danger small" onclick="permanentlyDeleteResource('${r.id}')">🗑 Delete Forever</button>`:r.archived?`<button class="btn success small" onclick="restoreArchivedResource('${r.id}')">↩ Restore</button>`:`<button class="btn secondary small" onclick="editResource('${r.id}')">✏ Edit</button><button class="btn secondary small" onclick="copyResourceLink('${r.id}')">📋 Copy</button><button class="btn secondary small" onclick="toggleResourcePin('${r.id}')">${r.pinned?"📌 Unpin":"📍 Pin"}</button><button class="btn secondary small" onclick="toggleResourceFavourite('${r.id}')">${r.favourite?"⭐ Unfavourite":"☆ Favourite"}</button><button class="btn warning small" onclick="archiveResource('${r.id}')">🗄 Archive</button><button class="btn danger small" onclick="deleteResource('${r.id}')">🗑 Delete</button>`}</div><div class="muted" style="margin-top:15px;font-size:13px;display:flex;gap:14px;flex-wrap:wrap"><span>📅 Added ${dateText(r.created)}</span><span>✏ Edited ${dateText(r.lastEdited)}</span><span>🕒 Last opened ${dateText(r.lastOpened)}</span><span>👆 ${r.clicks} opens</span></div>`;grid.appendChild(card)});updateResourceStats()}
function updateResourceStats(){if($("totalResources"))$("totalResources").textContent=resources.filter(r=>!r.deleted&&!r.archived).length;if($("totalFavourites"))$("totalFavourites").textContent=resources.filter(r=>r.favourite&&!r.deleted).length;if($("totalClicks"))$("totalClicks").textContent=resources.reduce((s,r)=>s+r.clicks,0);if($("totalSubjects"))$("totalSubjects").textContent=new Set(resources.filter(r=>!r.deleted).map(r=>r.subject)).size;if($("archivedCount"))$("archivedCount").textContent=resources.filter(r=>r.archived&&!r.deleted).length;if($("deletedCount"))$("deletedCount").textContent=resources.filter(r=>r.deleted).length;if($("libraryStatus"))$("libraryStatus").textContent=resources.length?`${resources.length} resources stored locally.`:"Your library is empty."}
function editResource(id){const r=resources.find(x=>x.id===id);if(!r)return;const title=prompt("Title",r.title);if(title===null)return;const url=prompt("URL",r.url);if(url===null)return;const tag=prompt("Topic / Tag",r.tag);if(tag===null)return;const note=prompt("Notes",r.note);if(note===null)return;r.title=title.trim()||r.title;r.url=url.trim()||r.url;r.tag=tag.trim();r.note=note.trim();r.lastEdited=Date.now();saveResources();renderResources()}
function toggleResourcePin(id){const r=resources.find(x=>x.id===id);if(r){r.pinned=!r.pinned;saveResources();renderResources()}}
function toggleResourceFavourite(id){const r=resources.find(x=>x.id===id);if(r){r.favourite=!r.favourite;saveResources();renderResources()}}
function archiveResource(id){const r=resources.find(x=>x.id===id);if(r&&confirm("Archive this resource?")){r.archived=true;saveResources();renderResources()}}
function deleteResource(id){const r=resources.find(x=>x.id===id);if(r&&confirm("Move this resource to the Recycle Bin?")){r.deleted=true;r.deletedDate=Date.now();saveResources();renderResources()}}
function restoreArchivedResource(id){const r=resources.find(x=>x.id===id);if(r){r.archived=false;showArchived=false;saveResources();renderResources()}}
function restoreDeletedResource(id){const r=resources.find(x=>x.id===id);if(r){r.deleted=false;r.deletedDate=null;showDeleted=false;saveResources();renderResources()}}
function permanentlyDeleteResource(id){if(!confirm("Permanently delete this resource? This cannot be undone."))return;resources=resources.filter(r=>r.id!==id);saveResources();renderResources()}
function trackResourceOpen(id){const r=resources.find(x=>x.id===id);if(r){r.clicks++;r.lastOpened=Date.now();saveResources()}}
async function copyResourceLink(id){const r=resources.find(x=>x.id===id);if(!r)return;try{await navigator.clipboard.writeText(r.url);alert("Link copied.")}catch{prompt("Copy this link:",r.url)}}
function exportResourceLibrary(){const blob=new Blob([JSON.stringify(resources,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="gcse-ontrack-resources.json";document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),500)}
function importResourceLibrary(file){const reader=new FileReader();reader.onload=()=>{try{const incoming=JSON.parse(reader.result);if(!Array.isArray(incoming))throw 0;const ids=new Set(resources.map(r=>r.id));incoming.map(normalise).forEach(r=>{if(!ids.has(r.id))resources.push(r)});saveResources();renderResources();alert("Library imported.")}catch{alert("Invalid resource backup.")}};reader.readAsText(file)}
function openSelectedSubject(){const subject=$("subjectInput").value;if(!subject)return alert("Choose a subject.");const list=resources.filter(r=>r.subject===subject&&!r.deleted&&!r.archived);if(!list.length)return alert("No active resources found for this subject.");if(openNewTab)list.forEach(r=>window.open(r.url,"_blank","noopener"));else window.location.href=list[0].url}
document.addEventListener("DOMContentLoaded",()=>{if(!$("resourceGrid"))return;$("addResourceBtn")?.addEventListener("click",addResource);$("searchInput")?.addEventListener("input",e=>{currentSearch=e.target.value;renderResources()});$("subjectFilter")?.addEventListener("change",e=>{currentSubject=e.target.value;renderResources()});$("sortSelect")?.addEventListener("change",e=>{currentSort=e.target.value;renderResources()});$("resetFiltersBtn")?.addEventListener("click",()=>{currentSearch="";currentSubject="All Subjects";currentSort="newest";showArchived=false;showDeleted=false;$("searchInput").value="";$("subjectFilter").value="All Subjects";$("sortSelect").value="newest";renderResources()});$("toggleTabMode")?.addEventListener("click",e=>{openNewTab=!openNewTab;e.currentTarget.textContent=openNewTab?"🌐 New Tab":"📄 Same Tab"});$("exportBtn")?.addEventListener("click",exportResourceLibrary);$("importBtn")?.addEventListener("click",()=>$("importFile")?.click());$("importFile")?.addEventListener("change",e=>{if(e.target.files[0])importResourceLibrary(e.target.files[0]);e.target.value=""});$("clearLibraryBtn")?.addEventListener("click",()=>{if(confirm("Delete every resource? This cannot be undone.")){resources=[];saveResources();renderResources()}});$("archiveBtn")?.addEventListener("click",()=>{showArchived=true;showDeleted=false;renderResources()});$("recycleBinBtn")?.addEventListener("click",()=>{showDeleted=true;showArchived=false;renderResources()});$("openSubjectBtn")?.addEventListener("click",openSelectedSubject);renderResources()});
