/* GCSE OnTrack — Timetable engine */
const DAYS=["Mon","Tue","Wed","Thu","Fri","Sat","Sun"],TIMES=["09:00","10:00","11:00","12:00","13:00","14:00","15:00","16:00","17:00","18:00","19:00","20:00"],TT_KEY="ontrack_timetable_final";
const $=id=>document.getElementById(id);
function getTimetable(){try{return JSON.parse(localStorage.getItem(TT_KEY)||"{}")}catch{return{}}}
function saveTimetable(d){localStorage.setItem(TT_KEY,JSON.stringify(d))}
function renderTimetable(){const grid=$("ttGrid");if(!grid)return;const data=getTimetable();grid.innerHTML="";const h=document.createElement("div");h.className="ttHead";h.textContent="Time";grid.appendChild(h);DAYS.forEach(d=>{const e=document.createElement("div");e.className="ttHead";e.textContent=d;grid.appendChild(e)});TIMES.forEach(t=>{const te=document.createElement("div");te.className="ttTime";te.textContent=t;grid.appendChild(te);DAYS.forEach(d=>{const cell=document.createElement("div");cell.className="ttCell";const k=d+"_"+t;(Array.isArray(data[k])?data[k]:[]).forEach((task,i)=>{const block=document.createElement("div");block.className="ttBlock";const strong=document.createElement("strong");strong.textContent=task;block.appendChild(strong);const small=document.createElement("small");small.textContent=`${d} • ${t}`;block.appendChild(small);const btn=document.createElement("button");btn.className="btn danger small";btn.textContent="Remove";btn.addEventListener("click",()=>removeBlock(d,t,i));block.appendChild(btn);cell.appendChild(block)});grid.appendChild(cell)})})}
function addTimetableBlock(){const d=$("day")?.value,t=$("time")?.value,task=$("task")?.value.trim();if(!task)return alert("Enter a subject or task.");const data=getTimetable(),k=d+"_"+t;if(!Array.isArray(data[k]))data[k]=[];data[k].push(task);saveTimetable(data);$("task").value="";renderTimetable()}
function removeBlock(d,t,i){const data=getTimetable(),k=d+"_"+t;if(!Array.isArray(data[k]))return;data[k].splice(i,1);if(!data[k].length)delete data[k];saveTimetable(data);renderTimetable()}
function clearTimetable(){if(!confirm("Clear the entire timetable? This cannot be undone."))return;localStorage.removeItem(TT_KEY);renderTimetable()}
document.addEventListener("DOMContentLoaded",()=>{if(!$("timetablePage"))return;$("addBlock")?.addEventListener("click",addTimetableBlock);$("clearTT")?.addEventListener("click",clearTimetable);$("timetableForm")?.addEventListener("submit",e=>{e.preventDefault();addTimetableBlock()});renderTimetable()});
